version: '2.4'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'