version: '2.4'
services:
  mysql:
    image: postgres:14
    container_name: scripts_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    container_name: scripts_redis
    restart: always
    ports:
      - '6379:6379'
