version: '2.4'
services:
  mysql:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
